<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
	public function myfind($id){
		$qb= $this->createQueryBuilder('a');
		$qb ->select('a')
			->where('a.id= :id')
			->setParameter('id', $id);
		return $qb -> getQuery()->getResult();
	}
}
