<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findArray($array){
		$qb= $this->createQueryBuilder('a');
		$qb ->select('a')
			->where('a IN (:array)')
			->setParameter('array', $array);
		return $qb -> getQuery()->getResult();
	}

	public function myfind($cat){
		$qb= $this->createQueryBuilder('a');
		$qb ->select('a','u')
			->leftJoin('a.categorie','u') 
			->where('u.nom= :categorie')
			->setParameter('categorie', $cat);
		return $qb -> getQuery()->getResult();
	}
}
